//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeBase.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbModel : DbContext
    {
        public DbModel()
            : base("name=DbModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Keywords> Keywords { get; set; }
        public virtual DbSet<Links> Links { get; set; }
        public virtual DbSet<LinksKeywords> LinksKeywords { get; set; }

        public System.Data.Entity.DbSet<KnowledgeBase.Models.LinkViewModel> LinkViewModels { get; set; }
    }
}
