//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeBase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinksKeywords
    {
        public int ID { get; set; }
        public int LinkID { get; set; }
        public int KeywordID { get; set; }
    
        public virtual Keywords Keywords { get; set; }
        public virtual Links Links { get; set; }
    }
}
